// ── Demo users ──
export const demoUsers = [
  { id: 1, name: 'Admin User', email: 'admin@solar.com', phone: '9876543210', role: 'admin' },
  { id: 2, name: 'Ravi Kumar', email: 'ravi@solar.com', phone: '9876543211', role: 'employee' },
  { id: 3, name: 'Sneha Reddy', email: 'sneha@solar.com', phone: '9876543212', role: 'employee' },
  { id: 4, name: 'Medha Dev', email: 'dev@solar.com', phone: '9876543213', role: 'admin' },
  { id: 5, name: 'Sunil Electricals', email: 'sunil@solar.com', phone: '9876543214', role: 'electrician' },
  { id: 6, name: 'Dwaraka Group Service', email: 'dwaraka@solar.com', phone: '9876543215', role: 'dwaraka' },
];

// passwords: admin123, ravi123, sneha123, dev123, sunil123, dwaraka123
export const demoPasswords = {
  'admin@solar.com': 'admin123',
  'ravi@solar.com': 'ravi123',
  'sneha@solar.com': 'sneha123',
  'dev@solar.com': 'dev123',
  'sunil@solar.com': 'sunil123',
  'dwaraka@solar.com': 'dwaraka123',
};

// ── Projects ──
export const demoProjects = [
  {
    id: 1, project_name: '10kW Rooftop – Jubilee Hills', customer_name: 'Rajesh Kumar',
    customer_email: 'rajesh@gmail.com', customer_phone: '9988776655',
    village: 'Jubilee Hills', site_address: 'Plot 42, Jubilee Hills, Hyderabad', system_size_kw: 10,
    panel_type: 'Mono PERC 540W', panel_count: 20, inverter_type: 'Growatt 10kW Hybrid',
    inverter_count: 1, project_cost: 650000, status: 'completed',
    start_date: '2025-11-15', expected_completion: '2025-12-15', actual_completion: '2025-12-10',
    notes: 'Net metering approved. Customer very satisfied.', created_by: 2,
    created_at: '2025-11-10T10:00:00Z',
  },
  {
    id: 2, project_name: '100kW Ground Mount – Vizag Factory', customer_name: 'Priya Sharma',
    customer_email: 'priya@textiles.com', customer_phone: '9876501234',
    village: 'Vizag', site_address: 'Industrial Area, Vizag', system_size_kw: 100,
    panel_type: 'Bifacial 545W', panel_count: 200, inverter_type: 'Sungrow 100kW',
    inverter_count: 1, project_cost: 5500000, status: 'completed',
    start_date: '2025-09-01', expected_completion: '2025-11-30', actual_completion: '2025-11-20',
    notes: 'Monitoring dashboard installed. ROI in 3.2 years.', created_by: 2,
    created_at: '2025-08-20T10:00:00Z',
  },
  {
    id: 3, project_name: '5kW Residential – Madhapur', customer_name: 'Anita Desai',
    customer_email: 'anita.d@gmail.com', customer_phone: '9123456789',
    village: 'Madhapur', site_address: '12-B, Madhapur Main Rd, Hyderabad', system_size_kw: 5,
    panel_type: 'Mono PERC 540W', panel_count: 10, inverter_type: 'Fronius 5kW',
    inverter_count: 1, project_cost: 350000, status: 'in_progress',
    start_date: '2026-03-10', expected_completion: '2026-04-15', actual_completion: null,
    notes: 'Subsidy application submitted under PM Surya Ghar.', created_by: 3,
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 4, project_name: '50kW Hospital Backup – Secunderabad', customer_name: 'Dr. Anand Rao',
    customer_email: 'anand@hospital.com', customer_phone: '9090909090',
    village: 'Secunderabad', site_address: 'MG Road, Secunderabad', system_size_kw: 50,
    panel_type: 'Bifacial 545W', panel_count: 100, inverter_type: 'Huawei 50kW',
    inverter_count: 1, project_cost: 3200000, status: 'in_progress',
    start_date: '2026-02-01', expected_completion: '2026-05-01', actual_completion: null,
    notes: 'Battery backup 20kWh with auto-switchover.', created_by: 2,
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 5, project_name: '3kW Rooftop – Kukatpally', customer_name: 'Suresh Babu',
    customer_email: 'suresh@gmail.com', customer_phone: '9012345678',
    village: 'Kukatpally', site_address: 'Flat 302, Green Heights, Kukatpally', system_size_kw: 3,
    panel_type: 'Mono PERC 540W', panel_count: 6, inverter_type: 'Growatt 3kW',
    inverter_count: 1, project_cost: 210000, status: 'planning',
    start_date: '2026-04-20', expected_completion: '2026-05-10', actual_completion: null,
    notes: 'Site survey done. Waiting for subsidy approval.', created_by: 3,
    created_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 6, project_name: '8kW Rooftop – Gachibowli', customer_name: 'Meena Patel',
    customer_email: 'meena@gmail.com', customer_phone: '9871234567',
    village: 'Gachibowli', site_address: 'Villa 12, Gachibowli', system_size_kw: 8,
    panel_type: 'Mono PERC 540W', panel_count: 16, inverter_type: 'Growatt 10kW Hybrid',
    inverter_count: 1, project_cost: 520000, status: 'completed',
    start_date: '2025-07-01', expected_completion: '2025-08-01', actual_completion: '2025-07-28',
    notes: 'Roof reinforcement done.', created_by: 2,
    created_at: '2025-06-20T10:00:00Z',
  },
  {
    id: 7, project_name: '15kW Commercial – Madhapur', customer_name: 'Tech Solutions Ltd',
    customer_email: 'info@techsol.com', customer_phone: '9800112233',
    village: 'Madhapur', site_address: 'IT Park, Madhapur', system_size_kw: 15,
    panel_type: 'Bifacial 545W', panel_count: 28, inverter_type: 'Huawei 15kW',
    inverter_count: 1, project_cost: 980000, status: 'completed',
    start_date: '2025-10-01', expected_completion: '2025-11-15', actual_completion: '2025-11-10',
    notes: 'Office rooftop installation.', created_by: 3,
    created_at: '2025-09-25T10:00:00Z',
  },
  {
    id: 8, project_name: '20kW School Rooftop – Vizag', customer_name: 'Sunrise School',
    customer_email: 'admin@sunrise.edu', customer_phone: '9700998877',
    village: 'Vizag', site_address: 'Beach Road, Vizag', system_size_kw: 20,
    panel_type: 'Mono PERC 540W', panel_count: 40, inverter_type: 'Growatt 20kW',
    inverter_count: 1, project_cost: 1300000, status: 'in_progress',
    start_date: '2026-01-15', expected_completion: '2026-03-15', actual_completion: null,
    notes: 'Government subsidized project.', created_by: 2,
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 9, project_name: '6kW Residential – Jubilee Hills', customer_name: 'Kiran Rao',
    customer_email: 'kiran@gmail.com', customer_phone: '9876001122',
    village: 'Jubilee Hills', site_address: 'Road No 10, Jubilee Hills', system_size_kw: 6,
    panel_type: 'Mono PERC 540W', panel_count: 12, inverter_type: 'Fronius 6kW',
    inverter_count: 1, project_cost: 420000, status: 'completed',
    start_date: '2026-01-10', expected_completion: '2026-02-10', actual_completion: '2026-02-05',
    notes: 'Battery backup added.', created_by: 3,
    created_at: '2026-01-05T10:00:00Z',
  },
  {
    id: 10, project_name: '4kW Residential – Kukatpally', customer_name: 'Venkat Reddy',
    customer_email: 'venkat.r@gmail.com', customer_phone: '9012009900',
    village: 'Kukatpally', site_address: 'KPHB Colony, Kukatpally', system_size_kw: 4,
    panel_type: 'Mono PERC 540W', panel_count: 8, inverter_type: 'Growatt 5kW',
    inverter_count: 1, project_cost: 280000, status: 'completed',
    start_date: '2025-12-01', expected_completion: '2025-12-30', actual_completion: '2025-12-25',
    notes: 'Net metering applied.', created_by: 2,
    created_at: '2025-11-25T10:00:00Z',
  },
  {
    id: 11, project_name: '25kW Warehouse – Secunderabad', customer_name: 'GoDown Logistics',
    customer_email: 'ops@godown.com', customer_phone: '9090112233',
    village: 'Secunderabad', site_address: 'Bowenpally, Secunderabad', system_size_kw: 25,
    panel_type: 'Bifacial 545W', panel_count: 50, inverter_type: 'Sungrow 25kW',
    inverter_count: 1, project_cost: 1650000, status: 'planning',
    start_date: '2026-05-01', expected_completion: '2026-06-30', actual_completion: null,
    notes: 'Large warehouse rooftop.', created_by: 3,
    created_at: '2026-04-05T10:00:00Z',
  },
  {
    id: 12, project_name: '12kW Farmhouse – Gachibowli', customer_name: 'Srinivas Murthy',
    customer_email: 'srini@farm.com', customer_phone: '9823456700',
    village: 'Gachibowli', site_address: 'Nanakramguda, Gachibowli', system_size_kw: 12,
    panel_type: 'Bifacial 545W', panel_count: 24, inverter_type: 'Huawei 12kW',
    inverter_count: 1, project_cost: 780000, status: 'in_progress',
    start_date: '2026-03-01', expected_completion: '2026-04-30', actual_completion: null,
    notes: 'Off-grid with battery.', created_by: 2,
    created_at: '2026-02-25T10:00:00Z',
  },
];

// ── Invoices ──
export const demoInvoices = [
  {
    id: 1, invoice_number: 'INV-20251210-0001', project_id: 1,
    project_name: '10kW Rooftop – Jubilee Hills', customer_name: 'Rajesh Kumar',
    customer_email: 'rajesh@gmail.com', subtotal: 585000, tax_percent: 12,
    tax_amount: 70200, total_amount: 655200, status: 'paid',
    due_date: '2026-01-10', paid_date: '2025-12-28',
    notes: 'Full payment received via NEFT.',
    created_at: '2025-12-10T10:00:00Z',
    items: [
      { id: 1, description: 'Mono PERC 540W Panels (x20)', quantity: 20, unit_price: 18000, total: 360000 },
      { id: 2, description: 'Growatt 10kW Hybrid Inverter', quantity: 1, unit_price: 125000, total: 125000 },
      { id: 3, description: 'Mounting Structure & Wiring', quantity: 1, unit_price: 60000, total: 60000 },
      { id: 4, description: 'Installation & Commissioning', quantity: 1, unit_price: 40000, total: 40000 },
    ],
  },
  {
    id: 2, invoice_number: 'INV-20251120-0002', project_id: 2,
    project_name: '100kW Ground Mount – Vizag Factory', customer_name: 'Priya Sharma',
    customer_email: 'priya@textiles.com', subtotal: 4900000, tax_percent: 12,
    tax_amount: 588000, total_amount: 5488000, status: 'paid',
    due_date: '2025-12-20', paid_date: '2025-12-15',
    notes: 'Payment in 2 installments.',
    created_at: '2025-11-20T10:00:00Z',
    items: [
      { id: 5, description: 'Bifacial 545W Panels (x200)', quantity: 200, unit_price: 17500, total: 3500000 },
      { id: 6, description: 'Sungrow 100kW Inverter', quantity: 1, unit_price: 650000, total: 650000 },
      { id: 7, description: 'Ground Mount Structure', quantity: 1, unit_price: 450000, total: 450000 },
      { id: 8, description: 'Monitoring Dashboard Setup', quantity: 1, unit_price: 100000, total: 100000 },
      { id: 9, description: 'Installation & Testing', quantity: 1, unit_price: 200000, total: 200000 },
    ],
  },
  {
    id: 3, invoice_number: 'INV-20260310-0003', project_id: 3,
    project_name: '5kW Residential – Madhapur', customer_name: 'Anita Desai',
    customer_email: 'anita.d@gmail.com', subtotal: 315000, tax_percent: 12,
    tax_amount: 37800, total_amount: 352800, status: 'sent',
    due_date: '2026-04-10', paid_date: null,
    notes: 'Advance 50% received. Balance on completion.',
    created_at: '2026-03-10T10:00:00Z',
    items: [
      { id: 10, description: 'Mono PERC 540W Panels (x10)', quantity: 10, unit_price: 18000, total: 180000 },
      { id: 11, description: 'Fronius 5kW Inverter', quantity: 1, unit_price: 85000, total: 85000 },
      { id: 12, description: 'Mounting + Wiring + Installation', quantity: 1, unit_price: 50000, total: 50000 },
    ],
  },
];

// ── Inventory ──
export const demoInventory = [
  { id: 1, item_name: 'Mono PERC 540W Panel', sku: 'PNL-MONO-540', category: 'panel', quantity: 120, unit: 'piece', min_stock_level: 50, unit_price: 18000, supplier: 'Adani Solar', location: 'Warehouse A', notes: 'Tier-1 panels, 25-yr warranty' },
  { id: 2, item_name: 'Bifacial 545W Panel', sku: 'PNL-BFCL-545', category: 'panel', quantity: 45, unit: 'piece', min_stock_level: 30, unit_price: 17500, supplier: 'Trina Solar', location: 'Warehouse A', notes: 'For ground mount & carport' },
  { id: 3, item_name: 'Growatt 10kW Hybrid Inverter', sku: 'INV-GRW-10H', category: 'inverter', quantity: 8, unit: 'piece', min_stock_level: 5, unit_price: 125000, supplier: 'Growatt India', location: 'Warehouse B', notes: 'Popular for residential' },
  { id: 4, item_name: 'Growatt 3kW Inverter', sku: 'INV-GRW-3K', category: 'inverter', quantity: 3, unit: 'piece', min_stock_level: 5, unit_price: 45000, supplier: 'Growatt India', location: 'Warehouse B', notes: 'Low stock — reorder' },
  { id: 5, item_name: 'Lithium Battery 10kWh', sku: 'BAT-LI-10K', category: 'battery', quantity: 6, unit: 'piece', min_stock_level: 3, unit_price: 320000, supplier: 'BYD Energy', location: 'Warehouse B', notes: 'For hybrid systems' },
  { id: 6, item_name: 'Rooftop Mounting Rail (3m)', sku: 'MNT-RAIL-3M', category: 'mounting', quantity: 200, unit: 'piece', min_stock_level: 100, unit_price: 850, supplier: 'SolarEdge Mounts', location: 'Warehouse A', notes: 'Aluminium, corrosion-resistant' },
  { id: 7, item_name: 'DC Cable 4mm² (100m roll)', sku: 'WR-DC4-100', category: 'wire', quantity: 35, unit: 'roll', min_stock_level: 20, unit_price: 4500, supplier: 'Polycab', location: 'Warehouse A', notes: 'Solar-rated, UV resistant' },
  { id: 8, item_name: 'MC4 Connector Pair', sku: 'CON-MC4-PR', category: 'connector', quantity: 500, unit: 'pair', min_stock_level: 200, unit_price: 120, supplier: 'Staubli', location: 'Warehouse A', notes: 'IP67 rated' },
  { id: 9, item_name: 'Sungrow 100kW Inverter', sku: 'INV-SG-100K', category: 'inverter', quantity: 2, unit: 'piece', min_stock_level: 2, unit_price: 650000, supplier: 'Sungrow India', location: 'Warehouse B', notes: 'Commercial grade' },
  { id: 10, item_name: 'Surge Protection Device', sku: 'OTH-SPD-DC', category: 'other', quantity: 25, unit: 'piece', min_stock_level: 10, unit_price: 3500, supplier: 'Havells', location: 'Warehouse A', notes: 'Type II DC SPD' },
];

// ── Maintenance Requests ──
export const demoMaintenance = [
  {
    id: 1, project_id: 1, project_name: '10kW Rooftop – Jubilee Hills',
    issue_type: 'panel_cleaning', priority: 'medium', status: 'completed',
    description: 'Annual maintenance check — panel cleaning and inverter inspection.',
    assigned_to: 'dwaraka_group', electrician_name: 'Venkat Rao', electrician_phone: '9000100001',
    scheduled_date: '2026-03-15', completed_date: '2026-03-15',
    resolution_notes: 'All panels cleaned. Inverter firmware updated. System performing at 98%.',
    amount: 5000, payment_status: 'paid', photo_1: null, photo_2: null,
    created_by: 2, requested_by_name: 'Ravi Kumar',
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 2, project_id: 3, project_name: '5kW Residential – Madhapur',
    issue_type: 'inverter_repair', priority: 'high', status: 'in_progress',
    description: 'Inverter showing error E-011. System not generating power since yesterday.',
    assigned_to: 'local_electrician', electrician_name: 'Sunil Electricals', electrician_phone: '9876543214',
    scheduled_date: '2026-04-08', completed_date: null,
    resolution_notes: null,
    amount: 12000, payment_status: 'unpaid', photo_1: null, photo_2: null,
    created_by: 3, requested_by_name: 'Sneha Reddy',
    created_at: '2026-04-07T08:00:00Z',
  },
  {
    id: 3, project_id: 4, project_name: '50kW Hospital Backup – Secunderabad',
    issue_type: 'wiring_issue', priority: 'urgent', status: 'pending',
    description: 'Battery backup not switching over during power cuts. Critical for hospital operations.',
    assigned_to: 'dwaraka_group', electrician_name: '', electrician_phone: '',
    scheduled_date: null, completed_date: null,
    resolution_notes: null,
    amount: null, payment_status: 'unpaid', photo_1: null, photo_2: null,
    created_by: 2, requested_by_name: 'Ravi Kumar',
    created_at: '2026-04-08T06:00:00Z',
  },
  {
    id: 4, project_id: 2, project_name: '100kW Ground Mount – Vizag Factory',
    issue_type: 'panel_cleaning', priority: 'low', status: 'completed',
    description: 'Quarterly panel cleaning for ground mount array. Dust accumulation noted.',
    assigned_to: 'local_electrician', electrician_name: 'Sunil Electricals', electrician_phone: '9876543214',
    scheduled_date: '2026-02-20', completed_date: '2026-02-20',
    resolution_notes: 'All 200 panels cleaned with soft brush and DI water. Generation improved by 8%.',
    amount: 15000, payment_status: 'paid', photo_1: null, photo_2: null,
    created_by: 3, requested_by_name: 'Sneha Reddy',
    created_at: '2026-02-10T10:00:00Z',
  },
];
